# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: /posts/:title
paginate: 6 # the number of post per page
rdiscount:
  extensions: [smart]

# User Options
name: Ayush Tiwari
baseurl:   # Leave this blank unless you are using a directory other than the root directory (Do not use a trailing slash '/')
description: 'Python developer, mechanical researcher, avid trekker & a Jharkhand_ee'
email: tiwari.ayush2412@gmail.com
twitter: http://twitter.com/jharkhand_ee
icon_url: /images/scribble5.png
disqus_shortname: tiwariayush
worksurl: /works
abouturl: /about

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#385975'
header_text_color: '#dfe6ec'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background:

# Footer
footer_title:
footer_description:
social_links_title:
github_url: https://github.com/tiwariayush
flickr_url:
instagram_url: https://instagram.com/tiwaribaba
vimeo_url:
google_plus_url:
pinterest_url:
tumblr_url:
linkedin_url: https://in.linkedin.com/in/tiwariayush1
dribbble_url:
lastfm_url:
rdio_url:
spotify_url:
skype_url:
soundcloud_url:
behance_url:

theme: jekyll-theme-slate
